### ISSUE TITLE
Questions about sd-scripts and diffusers

### ISSUE THREAD

**Issue by elichan5168** [shirayu/tohoku_sd_lora#21]
Hi shirayu,

Your work on diffusion models is really impressive! I came across your example_lora_training repo (https://github.com/shirayu/example_lora_training) and as someone just starting to learn about diffusion, I've been working with sd-scripts and diffusers. I'd really appreciate if you could help me with a couple of questions.

1. Do you use regularization images in your training (https://github.com/shirayu/example_lora_training)? 
2. I recently tried training a LoRA model using the train_text_to_image_lora.py script from diffusers, with the image captions in a metadata file. However, the results were quite poor. On the other hand, when I tried using the LoRA in the Kohya_ss Web GUI with the image captions txt, I was able to generate my target images successfully. I'm not sure why there's such a difference since I didn't use any regularization images in either case. Could you explain the differences among the train_text_to_image_lora.py, train_dreambooth_lora.py scripts and sd-scripts?
3. Is the Kohya_ss LoRA button equivalent to using dreambooth+caption, but without the need for regularization images (since I didn't input any reg_img)? Also, is it possible to use the train_dreambooth_lora.py script from diffusers without regularization images?

Thanks for your help in advance.

**Comment by shirayu** [comment]
Hi!


1. The repository was created for the first LoRA experiments and is no longer maintained. I think I probably used regularized images.

2.  I have not done learning LoRA with diffusers at all recently.
Therefore, I am not able to give proper advice.
This is just my personal opinion, but I think sd-scripts is better maintained and you should use it.

3.  I have not used dreambooth at all recently, so I am afraid I cannot give you proper advice.

Finally, I think that the presence or absence of regularized images has little effect on learning, and that the other parameters are much more important.
In fact, I do not use regularized images at all these days.

If you need further advice, I recommend that you get it from the respective code community.

Thank you.
